id: P5B47448C
initial_creation_type: input
source_metadata:
  title: Exposition of the Cakrasaṃvaratantra (block print), colophon excerpt
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-08-19); revised, thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:ཀླུ་གྲུབ། (Gongkar Choede) (ld)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4868
  bases:
    6ad4:
      title: Exposition of the Cakrasaṃvaratantra (block print), colophon excerpt
      order: 1
      base_file: 6ad4.txt
created_at: '2022-04-15T18:42:00.656253'
last_modified_at: '2022-04-15T18:42:00.656259'
quality: null
